# Generated by Django 4.2.1 on 2023-06-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumple',
            name='fecha',
            field=models.DateField(),
        ),
    ]
