# Generated by Django 4.2.1 on 2023-06-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_users_alter_task_datecompleted_cumples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cumples',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='cumples',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
