# Generated by Django 4.2.1 on 2023-06-03 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_alter_cumples_fecha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cumples',
            new_name='Cumple',
        ),
        migrations.AlterField(
            model_name='cumple',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
