# Generated by Django 4.2.1 on 2023-06-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_cumples_cumple_alter_cumple_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cumple',
            name='description',
        ),
        migrations.AddField(
            model_name='cumple',
            name='descripcion',
            field=models.CharField(default='Cumpleañero', max_length=255),
        ),
        migrations.AlterField(
            model_name='cumple',
            name='fecha',
            field=models.DateField(max_length=200),
        ),
    ]
